### ISSUE TITLE
skip flag

### ISSUE THREAD

**Issue by knoxg** [leonardehrenfried/jspc-maven-plugin#104]
Most maven plugins have a skip configuration option which lets the user skip that plugin for a particular mvn invocation.

This is useful for things like CI pipelines, where a particular job in the pipeline may only need to run a subset of the mvn plugins; e.g. the `maven.main.skip` user property / skipMain configuration property which can be used to disable the maven-compiler-plugin plugin ( https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html )

It would be great if there was a similar flag to disable the jspc plugin.

**Comment by leonardehrenfried** [comment]
I'm happy to take a PR for this. Would you like to contribute it?

**Comment by knoxg** [comment]
Yep ok

**Comment by knoxg** [comment]
OK have created two PRs, one for the 4.x branch ( which will merge into master )
and another for the 3.x branch ( which is set to Draft as it also merges into master ).

Was going to set the 3.x PR to merge into the 3.x branch, but I didn't see one in your repository.
The source of that PR is branched from the jspc-maven-plugin-3.2.0 tag if your repository so might need to have the version bumped in the pom.xml back to the next SNAPSHOT version.

**Comment by knoxg** [comment]
New PR which sets the tomcat version back to 9.x on the 3.2 branch: https://github.com/leonardehrenfried/jspc-maven-plugin/pull/110

Thanks again :)

**Comment by knoxg** [comment]
The new plugin is working well, thanks, will resolve this issue.

**Comment by knoxg** [comment]
The new plugin is working well, thanks, will mark the issue resolved/closed.
