### ISSUE TITLE
Dependencies are out of date

### ISSUE THREAD

**Issue by leonardehrenfried** [leonardehrenfried/jspc-maven-plugin#12]
I've added a badge that shows the dependency versions. Most of them are out of date.

Crucially, there is a version 9 of the Jasper compiler. Is it worth upgrading to it?

The full report is here: https://www.versioneye.com/user/projects/59f845ff0fb24f1f1f38c657

@tcollignon Would you be able to update the dependencies?

**Comment by tcollignon** [comment]
Ok I Will take a look at this

**Comment by tcollignon** [comment]
For Jasper 9, maybe it will start a 3.X version of the plugin ?
We can bump to JDK 8 too ?
Maybe this can be on master branch, to start 3.X version, and you can create 2.X branch for maintenance if needed with JDK 7 and Jasper 8.X ?

**Comment by leonardehrenfried** [comment]
I'm happy with whatever you think is best, since you will be writing almost all of the code. 3.x is fine by me.

Java 7 has been EOL for almost 2 years so I won't be arguing for compatibility with it, but is there a specific feature in Java 8 that you would like to use?

**Comment by tcollignon** [comment]
Ok I will send a PR to start new 3.X version
For Java 8 no real specific feature, is just to move on! :)

**Comment by tcollignon** [comment]
This issue is now resolved, I close it
