### ISSUE TITLE
Support to disable "JAR was scanned for TLDs yet contained no TLDs" warning

### ISSUE THREAD

**Issue by rmozone** [leonardehrenfried/jspc-maven-plugin#24]
Hi guys! How can we suppress the _"JAR was scanned for TLDs yet contained no TLDs"_ warning?
I've managed to do this by setting the _tomcat.util.scan.StandardJarScanFilter.jarsToSkip_ system property to value _\*.jar_ when calling **mvn**. But, would be nicer to have a way to pass system properties to the forked jspc processes, avoiding to do it when calling **mvn**. That way, we could set this system property inside the pom.

**Comment by tcollignon** [comment]
Hi, 

I think I can see what you mean, but If you can provide a little project or configuration that you have to let me easier reproduce, it will be great
Thx

**Comment by leonardehrenfried** [comment]
Fixed by https://github.com/leonardehrenfried/jspc-maven-plugin/pull/211.

Please re-open if not.
