### ISSUE TITLE
Need java8 support

### ISSUE THREAD

**Issue by cindychaopeng** [leonardehrenfried/jspc-maven-plugin#27]
Will java8 support and dependencies upgrade be released soon? I ran into compile error, complaining about "The resource type ResourceResolver does not implement java.lang.AutoCloseable". I believe it is due to the old version of org.apache.sling.api 2.2.2 being used. In newer version of org.apache.sling.api(e.g. AEM6.2 is using 2.11.0), ResourceResolver does implement AutoCloseable.

**Comment by leonardehrenfried** [comment]
Additionally to what Thomas has said, Java8 is actually supported.

The tests in .travis.yml running under java8 (among other JVM versions).

**Comment by cindychaopeng** [comment]
Thanks for your quick response. I might have confused myself with what I have seen from https://sling.apache.org/components/jspc-maven-plugin/ with yours. Please ignore my issue.

**Comment by tcollignon** [comment]
thx @cindychaopeng , so we close the issue
