### ISSUE TITLE
 An API incompatibility was encountered while executing io.leonard.maven.plugins:jspc-maven-plugin:2.4.6:compile: java.lang.NoSuchFieldError: scanner

### ISSUE THREAD

**Issue by mattdandrea** [leonardehrenfried/jspc-maven-plugin#37]
I'm getting the following error when trying to upgrade from 2.4.1 to 2.4.6.

Execution jspc of goal io.leonard.maven.plugins:jspc-maven-plugin:2.4.6:compile failed: An API incompatibility was encountered while executing io.leonard.maven.plugins:jspc-maven-plugin:2.4.6:compile: java.lang.NoSuchFieldError: scanner

I'm using tomcat-jasper 7.0.59.
This works fine with 2.4.1 of the jspc-maven-plugin.

Thanks,

Matt

**Comment by tcollignon** [comment]
Hi
i will try to reproduce, and fix if I can. Otherwise you may need to stay in 2.4.1. What is your motivation to upgrade in 2.4.6 you need something?
Thanks

**Comment by mattdandrea** [comment]
I'm seeing a multi-threading issue and was hoping that https://github.com/leonardehrenfried/jspc-maven-plugin/issues/28 might fix it.

**Comment by tcollignon** [comment]
Ok

Is upgrading Tomcat a possibility or not ?
Regarding the [compatibility Matrix](https://github.com/leonardehrenfried/jspc-maven-plugin#compatibility-matrix) 2.X is normally for Tomcat 8.X

**Comment by tcollignon** [comment]
If you look at JspCContextAccessor#initContext you will see a Tomcat 8 dependency introduce by PR #16 
I'm sorry but you need to upgrade to Tomcat 8.X or keep 1.X, or keep your 2.4.1 (maybe 2.4.2)

**Comment by mattdandrea** [comment]
Would that threading issue affect 1.x though?

**Comment by mattdandrea** [comment]
Upgrading Tomcat is not an option presently no.

**Comment by tcollignon** [comment]
I don't be sure but if I remember there is no possible threading in 1.X

**Comment by tcollignon** [comment]
So I close the issue, sorry
