### ISSUE TITLE
Multi-threaded compilation mangles webXmlFragment

### ISSUE THREAD

**Issue by philflack** [leonardehrenfried/jspc-maven-plugin#9]
Hello,
I have been trying v2.2.0 with 8 threads for compiling JSPs and I think I have found a bug with the creation/merging of the webXmlFragment.  It looks like each of the JspC instances all use the same filename, which is then merged into the input web.xml.  However, this isn't working for me, and the fragment has some odd errors, which I guess are parts of fragments from some of the 8 threads.  

Not sure how it can be fixed - separate filename for each worker thread or in-memory fragment generation?

**Comment by leonardehrenfried** [comment]
In-memory generation seems like the way forward however I haven't worked on JSPs for over 5 years.

If you'd like to send a PR we'd gladly merge it in.

@tcollignon Can you shed some light on this?

**Comment by tcollignon** [comment]
Hi,

I don't use this parameter webXmlFragment actually. If you have a more concret example (like small project) it can be help to fix this
Thank you

**Comment by philflack** [comment]
Hi, sorry for the delay in responding.  I don't have a small project, and I suspect that this problem is much more likely to occur as the number of JSPs increases (seen with over 1400 spread over 8 threads).  

I am looking into how the webXmlFragment output file is supposed to be used (according to apache jasper); if this is working how I think (the fragment is only meant to be a temporary file), then I suggest adding a thread index to the user-supplied filename, i.e. webfrag.xml.1  or 1-webfrag.xml.

**Comment by tcollignon** [comment]
Hi, ok I see the bug, I will send a PR to fix this.
I will use the solution with thread index in the webfrag filename because it much easier to not change jasper behavior.

**Comment by tcollignon** [comment]
@philflack can you try the PR #10 and said to me if it fix your issue please?

**Comment by leonardehrenfried** [comment]
I've added a snapshot version 2.4.0-SNAPSHOT to the Sonatype repo.

@philflack Can you try it out? You can configure Sonatype snapshots like this: https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by leonardehrenfried** [comment]
I've released version 2.4.1. Should be on Maven Central in less than an hour.

@philflack If it doesn't solve the issue, please reopen/comment.

**Comment by tcollignon** [comment]
Hi @leonardehrenfried , maybe next time you can release RCX release? Like 2.4.1.RC.1 ?
